set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 21)
set(CMAKE_ANDROID_ARCH_ABI arm64)
set(CMAKE_ANDROID_NDK /mnt/e/WSL_Data/AndroidSDK/ndk/android-ndk-r25b)
set(CMAKE_ANDROID_STL_TYPE c++_static)
set(ANDROID_STL c++_static)
